<?php
declare(strict_types=1);
require_once __DIR__ . '/_university_shell.php';
$date=u_valid_date($_GET['date']??null)?:date('Y-m-d');
$rows=[];try{$rows=u_all($pdo,"SELECT s.schedule_id,s.departure_time,s.arrival_time,s.status,r.route_code,r.route_name,b.registration_number,b.seat_capacity,b.standing_capacity,COUNT(DISTINCT CASE WHEN bk.slot_type='SEAT' AND bk.status IN ('BOOKED','CONFIRMED','TRANSFER_PENDING') THEN bk.booking_id END) booked_seats,COUNT(DISTINCT CASE WHEN bk.slot_type='STANDING' AND bk.status IN ('BOOKED','CONFIRMED','TRANSFER_PENDING') THEN bk.booking_id END) booked_standing FROM schedules s JOIN routes r ON r.route_id=s.route_id JOIN buses b ON b.bus_id=s.bus_id LEFT JOIN bookings bk ON bk.schedule_id=s.schedule_id WHERE r.university_id=? AND b.university_id=? AND s.schedule_date=? GROUP BY s.schedule_id,s.departure_time,s.arrival_time,s.status,r.route_code,r.route_name,b.registration_number,b.seat_capacity,b.standing_capacity ORDER BY s.departure_time",[$uUniversityId,$uUniversityId,$date]);}catch(Throwable $e){error_log('[UniRide occupancy] '.$e->getMessage());}
u_render_start('Occupancy','occupancy','Operations','Seat and standing usage calculated from live booking data for each schedule.');u_render_actions('<a class="up-button-secondary" href="bookings.php">Bookings</a>');u_render_heading_end();
?>
<form method="get" class="up-filter up-filter-date"><input type="date" name="date" value="<?= u_h($date) ?>"><button class="up-button-secondary" type="submit">View Date</button></form>
<?php if(!$rows): ?><div class="up-empty"><div><strong>No schedules on this date.</strong><p>Occupancy appears automatically when this university has scheduled trips.</p></div></div><?php else: ?><div class="up-table-wrap"><table class="up-table"><thead><tr><th>Route</th><th>Bus</th><th>Time</th><th>Seats</th><th>Standing</th><th>Seat Occupancy</th><th>Total Load</th><th>Status</th></tr></thead><tbody><?php foreach($rows as $r): $occ=u_percent((int)$r['booked_seats'],(int)$r['seat_capacity']);$load=(int)$r['booked_seats']+(int)$r['booked_standing'];$cap=(int)$r['seat_capacity']+(int)$r['standing_capacity']; ?><tr><td><strong><?= u_h($r['route_code']) ?></strong><small><?= u_h($r['route_name']) ?></small></td><td><?= u_h($r['registration_number']) ?></td><td><?= u_h(u_time($r['departure_time'])) ?> – <?= u_h(u_time($r['arrival_time'])) ?></td><td><?= (int)$r['booked_seats'] ?> / <?= (int)$r['seat_capacity'] ?></td><td><?= (int)$r['booked_standing'] ?> / <?= (int)$r['standing_capacity'] ?></td><td><div class="up-progress"><div class="up-progress-track"><span style="width:<?= min(100,$occ) ?>%"></span></div><strong><?= $occ ?>%</strong></div></td><td><?= $load ?> / <?= $cap ?></td><td><span class="up-status <?= u_h(u_status_class($r['status'])) ?>"><?= u_h($r['status']) ?></span></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
<?php u_render_end(); ?>
