<?php
declare(strict_types=1);
require_once __DIR__ . '/_university_shell.php';
if($_SERVER['REQUEST_METHOD']==='POST' && ($_POST['action']??'')==='add_route'){
    if(!u_verify_csrf($_POST['csrf_token']??null)){u_flash('error','Your session expired. Please try again.');u_redirect('routes.php?new=1');}
    $code=strtoupper(trim((string)($_POST['route_code']??'')));$name=trim((string)($_POST['route_name']??''));$start=trim((string)($_POST['start_location']??''));$end=trim((string)($_POST['end_location']??''));$fare=uniride_ticket_fare();
    if($code===''||$name===''||$start===''||$end===''){u_flash('error','Please complete all route fields.');u_redirect('routes.php?new=1');}
    try{$stmt=$pdo->prepare("INSERT INTO routes(university_id,route_code,route_name,start_location,end_location,fare,status) VALUES (?,?,?,?,?,?,'ACTIVE')");$stmt->execute([$uUniversityId,$code,$name,$start,$end,$fare]);u_flash('success','Route added to '.$uUniversity['name'].'.');u_redirect('routes.php');}catch(Throwable $e){error_log('[UniRide add route] '.$e->getMessage());u_flash('error','The route could not be added. Check for a duplicate route code.');u_redirect('routes.php?new=1');}
}
$rows=[];try{$rows=u_all($pdo,"SELECT r.route_id,r.route_code,r.route_name,r.start_location,r.end_location,r.fare,r.status,COUNT(DISTINCT s.schedule_id) schedules,COUNT(DISTINCT CASE WHEN s.schedule_date>=CURDATE() AND s.status='SCHEDULED' THEN s.schedule_id END) upcoming FROM routes r LEFT JOIN schedules s ON s.route_id=r.route_id WHERE r.university_id=? GROUP BY r.route_id,r.route_code,r.route_name,r.start_location,r.end_location,r.fare,r.status ORDER BY CASE r.status WHEN 'ACTIVE' THEN 0 ELSE 1 END,r.route_code",[$uUniversityId]);}catch(Throwable $e){error_log('[UniRide routes] '.$e->getMessage());}
u_render_start('Routes','routes','Operations','Manage route definitions, fares and schedule coverage for this university.');u_render_actions('<a class="up-button" href="routes.php?new=1">+ Add Route</a><a class="up-button-secondary" href="route-stops.php">Route Stops</a>');u_render_heading_end();
?>
<?php if(isset($_GET['new'])): ?><section class="up-card blue" style="margin-bottom:16px"><div class="section-heading-row"><div><p class="dashboard-kicker">New route</p><h2>Create Route</h2></div></div><form method="post" class="up-form-grid"><input type="hidden" name="csrf_token" value="<?= u_h(u_csrf()) ?>"><input type="hidden" name="action" value="add_route"><label class="up-field"><span>Route code</span><input name="route_code" placeholder="<?= u_h($uUniversity['code']) ?>-R01" required></label><label class="up-field"><span>Route name</span><input name="route_name" required></label><label class="up-field"><span>Start location</span><input name="start_location" required></label><label class="up-field"><span>End location</span><input name="end_location" required></label><label class="up-field"><span>Fare (BDT)</span><input type="number" value="<?= u_h(number_format(uniride_ticket_fare(),2,'.','')) ?>" readonly></label><div class="up-form-actions"><button class="up-button" type="submit">Save Route</button><a class="up-button-secondary" href="routes.php">Cancel</a></div></form></section><?php endif; ?>
<?php if(!$rows): ?><div class="up-empty"><div><strong>No routes configured.</strong><p>Create the first route for this university.</p></div><a class="up-button" href="?new=1">Add Route</a></div><?php else: ?><div class="up-table-wrap"><table class="up-table"><thead><tr><th>Code</th><th>Route</th><th>Start</th><th>End</th><th>Fare</th><th>Schedules</th><th>Upcoming</th><th>Status</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><strong><?= u_h($r['route_code']) ?></strong></td><td><?= u_h($r['route_name']) ?></td><td><?= u_h($r['start_location']) ?></td><td><?= u_h($r['end_location']) ?></td><td>৳<?= number_format(uniride_ticket_fare(),0) ?></td><td><?= (int)$r['schedules'] ?></td><td><?= (int)$r['upcoming'] ?></td><td><span class="up-status <?= u_h(u_status_class($r['status'])) ?>"><?= u_h($r['status']) ?></span></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
<?php u_render_end(); ?>
