<?php
declare(strict_types=1);
require_once __DIR__ . '/_university_shell.php';
$tableReady=u_table_exists($pdo,'route_stops');
if($tableReady && $_SERVER['REQUEST_METHOD']==='POST' && ($_POST['action']??'')==='add_stop'){
    if(!u_verify_csrf($_POST['csrf_token']??null)){u_flash('error','Your session expired. Please try again.');u_redirect('route-stops.php');}
    $routeId=(int)($_POST['route_id']??0);$name=trim((string)($_POST['stop_name']??''));$order=max(1,(int)($_POST['stop_order']??1));
    $owned=(int)u_scalar($pdo,"SELECT COUNT(*) FROM routes WHERE route_id=? AND university_id=?",[$routeId,$uUniversityId]);
    if(!$owned||$name===''){u_flash('error','Choose one of your routes and enter a stop name.');u_redirect('route-stops.php');}
    try{$stmt=$pdo->prepare("INSERT INTO route_stops(route_id,stop_name,stop_order) VALUES (?,?,?)");$stmt->execute([$routeId,$name,$order]);u_flash('success','Route stop added.');}catch(Throwable $e){error_log('[UniRide add route stop] '.$e->getMessage());u_flash('error','The stop could not be added. That order may already be in use.');}u_redirect('route-stops.php');
}
$routes=[];$groups=[];try{$routes=u_all($pdo,"SELECT route_id,route_code,route_name FROM routes WHERE university_id=? AND status='ACTIVE' ORDER BY route_code",[$uUniversityId]);if($tableReady){$rows=u_all($pdo,"SELECT r.route_id,r.route_code,r.route_name,rs.stop_name,rs.stop_order FROM routes r LEFT JOIN route_stops rs ON rs.route_id=r.route_id WHERE r.university_id=? AND r.status='ACTIVE' ORDER BY r.route_code,rs.stop_order",[$uUniversityId]);foreach($rows as $r){$id=(int)$r['route_id'];$groups[$id]??=['code'=>$r['route_code'],'name'=>$r['route_name'],'stops'=>[]];if($r['stop_name']!==null)$groups[$id]['stops'][]=['name'=>$r['stop_name'],'order'=>(int)$r['stop_order']];}}}catch(Throwable $e){error_log('[UniRide route stops] '.$e->getMessage());}
u_render_start('Route Stops','route-stops','Operations','Configure the published stop sequence for this university’s active routes.');u_render_actions('<a class="up-button-secondary" href="routes.php">Manage Routes</a>');u_render_heading_end();
?>
<?php if(!$tableReady): ?><div class="up-note"><strong>Route stops are not enabled yet.</strong> Import <code>database/migrations/006_core_schema_consistency.sql</code>. Once the table exists, this same page works for every current and future university.</div><?php else: ?>
<section class="up-card blue" style="margin-bottom:16px"><div class="section-heading-row"><div><p class="dashboard-kicker">Stop sequence</p><h2>Add Stop</h2></div></div><form method="post" class="up-form-grid"><input type="hidden" name="csrf_token" value="<?= u_h(u_csrf()) ?>"><input type="hidden" name="action" value="add_stop"><label class="up-field"><span>Route</span><select name="route_id" required><option value="">Choose route</option><?php foreach($routes as $r): ?><option value="<?= (int)$r['route_id'] ?>"><?= u_h($r['route_code'].' · '.$r['route_name']) ?></option><?php endforeach; ?></select></label><label class="up-field"><span>Stop order</span><input type="number" name="stop_order" min="1" value="1" required></label><label class="up-field wide"><span>Stop name</span><input name="stop_name" required></label><div class="up-form-actions"><button class="up-button" type="submit">Add Stop</button></div></form></section>
<?php if(!$groups): ?><div class="up-empty"><div><strong>No active routes.</strong><p>Create routes before adding stops.</p></div></div><?php else: ?><div class="up-stop-grid"><?php foreach($groups as $g): ?><article class="up-stop-card"><h3><?= u_h($g['code']) ?></h3><p><?= u_h($g['name']) ?></p><?php if($g['stops']): ?><ol><?php foreach($g['stops'] as $s): ?><li><b><?= (int)$s['order'] ?></b><?= u_h($s['name']) ?></li><?php endforeach; ?></ol><?php else: ?><p>No stops configured.</p><?php endif; ?></article><?php endforeach; ?></div><?php endif; ?>
<?php endif; ?>
<?php u_render_end(); ?>
