<?php
declare(strict_types=1);
require_once __DIR__ . '/_university_shell.php';
if($_SERVER['REQUEST_METHOD']==='POST' && ($_POST['action']??'')==='update_fare'){
    if(!u_verify_csrf($_POST['csrf_token']??null)){u_flash('error','Your session expired. Please try again.');u_redirect('semester-fares.php');}
    $routeId=(int)($_POST['route_id']??0);$fare=uniride_ticket_fare();
    $stmt=$pdo->prepare("UPDATE routes SET fare=? WHERE route_id=? AND university_id=?");$stmt->execute([$fare,$routeId,$uUniversityId]);u_flash($stmt->rowCount()?'success':'error',$stmt->rowCount()?'Fare updated.':'No route fare was changed.');u_redirect('semester-fares.php');
}
$routes=u_all($pdo,"SELECT route_id,route_code,route_name,fare,status FROM routes WHERE university_id=? ORDER BY route_code",[$uUniversityId]);
$summary=['charges'=>0,'credits'=>0,'balance'=>0,'transactions'=>0];if($uSemester){try{$summary=array_merge($summary,u_one($pdo,"SELECT COALESCE(SUM(CASE WHEN bt.amount>0 THEN bt.amount ELSE 0 END),0) charges,COALESCE(SUM(CASE WHEN bt.amount<0 THEN ABS(bt.amount) ELSE 0 END),0) credits,COALESCE(SUM(bt.amount),0) balance,COUNT(DISTINCT bt.transaction_id) transactions FROM billing_transactions bt JOIN passengers p ON p.passenger_id=bt.passenger_id WHERE p.university_id=? AND bt.semester_id=?",[$uUniversityId,(int)$uSemester['semester_id']]));}catch(Throwable $e){error_log('[UniRide semester fares] '.$e->getMessage());}}
u_render_start('Semester & Fares','semester-fares','Configuration','Review the active semester and route fares belonging to this university.');u_render_heading_end();
?>
<section class="metric-grid"><article class="metric-card"><p>Active semester</p><strong style="font-size:22px"><?= u_h($uSemester['semester_name']??'None') ?></strong><span><?= u_h(isset($uSemester['start_date'])?u_date($uSemester['start_date']).' – '.u_date($uSemester['end_date']):'No active semester') ?></span></article><article class="metric-card"><p>Transport charges</p><strong>৳<?= number_format((float)$summary['charges'],0) ?></strong><span>Current semester</span></article><article class="metric-card"><p>Credits</p><strong>৳<?= number_format((float)$summary['credits'],0) ?></strong><span>Recorded adjustments</span></article><article class="metric-card"><p>Transactions</p><strong><?= number_format((int)$summary['transactions']) ?></strong><span>This university’s passengers</span></article></section>
<section class="dashboard-section"><div class="section-heading-row"><div><p class="dashboard-kicker">Route pricing</p><h2>Fares</h2><p>Every update is constrained by the session university.</p></div></div><?php if(!$routes): ?><div class="up-empty"><div><strong>No routes available.</strong><p>Create routes before configuring fares.</p></div></div><?php else: ?><div class="up-table-wrap"><table class="up-table"><thead><tr><th>Route</th><th>Name</th><th>Fare</th><th>Status</th><th>Update</th></tr></thead><tbody><?php foreach($routes as $r): ?><tr><td><strong><?= u_h($r['route_code']) ?></strong></td><td><?= u_h($r['route_name']) ?></td><td>৳<?= number_format(uniride_ticket_fare(),0) ?></td><td><span class="up-status <?= u_h(u_status_class($r['status'])) ?>"><?= u_h($r['status']) ?></span></td><td><form method="post" style="display:flex;gap:6px"><input type="hidden" name="csrf_token" value="<?= u_h(u_csrf()) ?>"><input type="hidden" name="action" value="update_fare"><input type="hidden" name="route_id" value="<?= (int)$r['route_id'] ?>"><input type="number" value="<?= u_h(number_format(uniride_ticket_fare(),2,'.','')) ?>" readonly style="width:90px;min-height:31px;border:1px solid #dce2e8;border-radius:7px;padding:0 7px"><button class="up-button-secondary" type="submit">Save</button></form></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
<?php u_render_end(); ?>
